const globalParamTexByKey: Record<string, string> = {
  g: "g",
  l: "l",
  l1: "l_1",
  l2: "l_2",
  m: "m",
  m1: "m_1",
  m2: "m_2",
  k: "k",
  mu: "\\mu",
  q: "q",
  u: "u",
  tau: "\\tau",
  hbar: "\\hbar",
  omega: "\\omega",
  theta0: "\\theta_0",
  phi0: "\\phi_0",
  theta1: "\\theta_1",
  phi1: "\\phi_1",
  theta2: "\\theta_2",
  phi2: "\\phi_2",
  x0: "x_0",
  y0: "y_0",
  x1: "x_1",
  y1: "y_1",
  xMin: "x_{\\min}",
  xMax: "x_{\\max}",
  yMin: "y_{\\min}",
  yMax: "y_{\\max}",
  gradStep: "\\Delta x_{\\nabla V}",
  gridPoints: "N",
  gridX: "N_x",
  gridY: "N_y",
  packetX0: "x_0",
  packetY0: "y_0",
  packetSigma: "\\sigma",
  packetSigmaX: "\\sigma_x",
  packetSigmaY: "\\sigma_y",
  packetK0: "k_0",
  packetK: "k",
  packetKx: "k_x",
  packetKy: "k_y",
  packetCenter: "x_0",
  packetWidth: "\\sigma",
  packetAmp: "A",
  packetPiScale: "\\alpha_{\\pi}",
  barrierCenter: "x_b",
  barrierY: "y_b",
  barrierWidth: "w_b",
  barrierThickness: "d_b",
  barrierHeight: "V_0",
  absorberStrength: "\\gamma_{\\mathrm{abs}}",
  absorberFraction: "f_{\\mathrm{abs}}",
  scanEmin: "E_{\\min}",
  scanEmax: "E_{\\max}",
  scanPoints: "N_E",
  wellWidth: "w_{\\mathrm{well}}",
  doubleBarrier: "b_{\\mathrm{dbl}}",
  sites: "N",
  hop: "t",
  epsilon0: "\\epsilon_0",
  disorderW: "W",
  disorderSeed: "s_{\\mathrm{dis}}",
  periodic: "b_{\\mathrm{per}}",
  impuritySite: "n_{\\mathrm{imp}}",
  impurityStrength: "V_{\\mathrm{imp}}",
  slitSeparation: "d_{\\mathrm{slit}}",
  slitWidth: "w_{\\mathrm{slit}}",
  slitPhase: "\\phi_{\\mathrm{slit}}",
  slitAmpRatio: "r_{\\mathrm{slit}}",
  carrierK: "k_c",
  rightSlitOpen: "b_{\\mathrm{right}}",
  detectorY: "y_{\\mathrm{det}}",
  mass: "m",
  lambda: "\\lambda",
  damping: "\\eta",
  c0: "c_0",
  c1: "c_1",
  c2: "c_2",
  fMax: "F_{\\max}",
  kPassive: "k_{\\mathrm{pas}}",
  lSlack: "l_{\\mathrm{slack}}",
  load: "F_{\\mathrm{load}}",
  lFloor: "l_{\\min}",
  muK: "\\mu_k",
  ex0: "E_{x0}",
  ey0: "E_{y0}",
  sourceStrength: "\\kappa_s",
  coreRadius: "r_c",
  uniformU: "U_0",
  uniformV: "V_0",
  vortexStrength: "\\Gamma",
  rhoFluid: "\\rho_f",
  rhoParticle: "\\rho_p",
  radius: "r_p",
  cd: "C_d",
  mCart: "m_c",
  mPole: "m_p",
  omegaX: "\\Omega_x",
  omegaY: "\\Omega_y",
  omegaZ: "\\Omega_z",
  omega1x: "\\Omega_{1x}",
  omega1y: "\\Omega_{1y}",
  omega1z: "\\Omega_{1z}",
  omega2x: "\\Omega_{2x}",
  omega2y: "\\Omega_{2y}",
  omega2z: "\\Omega_{2z}",
  jzz: "J_{zz}",
  segments: "N",
  iterations: "N_{\\mathrm{iter}}",
  learningRate: "\\alpha",
  smoothness: "\\lambda_s",
  xClustering: "\\beta_x"
};

const systemParamTexOverrides: Record<string, Record<string, string>> = {
  tightbinding: {
    packetCenter: "n_0"
  },
  qftlattice: {
    packetCenter: "x_0"
  }
};

export function getParamTexLabel(systemId: string | null, key: string): string | null {
  const override = systemId ? systemParamTexOverrides[systemId]?.[key] : undefined;
  if (typeof override === "string") {
    return override || null;
  }

  return globalParamTexByKey[key] ?? null;
}
