const globalParamTexByKey: Record<string, string> = {
  g: "g",
  l: "l",
  l1: "l_1",
  l2: "l_2",
  m: "m",
  m1: "m_1",
  m2: "m_2",
  k: "k",
  c: "c",
  mu: "\\mu",
  gamma: "\\gamma",
  q: "q",
  qProj: "q_{\\mathrm{proj}}",
  qTarget: "q_{\\mathrm{tgt}}",
  kC: "k_C",
  inertia: "I",
  I1: "I_1",
  I2: "I_2",
  drag: "\\gamma_v",
  drag1: "\\gamma_{v1}",
  drag2: "\\gamma_{v2}",
  rotDrag: "\\gamma_\\omega",
  rotDrag1: "\\gamma_{\\omega1}",
  rotDrag2: "\\gamma_{\\omega2}",
  u: "u",
  tau: "\\tau",
  hbar: "\\hbar",
  cWave: "c_w",
  omega: "\\omega",
  theta0: "\\theta_0",
  phi0: "\\phi_0",
  theta1: "\\theta_1",
  phi1: "\\phi_1",
  theta2: "\\theta_2",
  phi2: "\\phi_2",
  x0: "x_0",
  y0: "y_0",
  x1: "x_1",
  xStart: "x_{\\mathrm{start}}",
  y1: "y_1",
  xMin: "x_{\\min}",
  xMax: "x_{\\max}",
  yMin: "y_{\\min}",
  yMax: "y_{\\max}",
  gradStep: "\\Delta x_{\\nabla V}",
  gridSize: "N",
  gridPoints: "N",
  gridX: "N_x",
  gridY: "N_y",
  pressureIters: "N_{\\mathrm{proj}}",
  packetX0: "x_0",
  packetY0: "y_0",
  packetSigma: "\\sigma",
  packetSigmaX: "\\sigma_x",
  packetSigmaY: "\\sigma_y",
  packetK0: "k_0",
  packetK: "k",
  packetKx: "k_x",
  packetKy: "k_y",
  packetCenter: "x_0",
  packetWidth: "\\sigma",
  packetAmp: "A",
  packetPiScale: "\\alpha_{\\pi}",
  barrierCenter: "x_b",
  barrierY: "y_b",
  barrierWidth: "w_b",
  barrierThickness: "d_b",
  barrierHeight: "V_0",
  absorberStrength: "\\gamma_{\\mathrm{abs}}",
  absorberFraction: "f_{\\mathrm{abs}}",
  scanEmin: "E_{\\min}",
  scanEmax: "E_{\\max}",
  scanPoints: "N_E",
  pOcc: "p",
  trials: "N_{\\mathrm{trial}}",
  scanMin: "p_{\\min}",
  scanMax: "p_{\\max}",
  wellWidth: "w_{\\mathrm{well}}",
  wellSeparation: "d_{\\mathrm{well}}",
  doubleBarrier: "b_{\\mathrm{dbl}}",
  tilt: "\\epsilon",
  startInRight: "b_{\\mathrm{R0}}",
  bindRadius: "r_{\\mathrm{bind}}",
  bindWidth: "\\sigma_{\\mathrm{bind}}",
  kRep: "k_{\\mathrm{rep}}",
  kAttr: "k_{\\mathrm{att}}",
  kTorque: "k_{\\tau}",
  patchSharpness: "n_{\\mathrm{patch}}",
  thetaR: "\\theta_R",
  dropX0: "x_{\\mathrm{drop}}",
  dropY0: "y_{\\mathrm{drop}}",
  dropSigma: "\\sigma_{\\mathrm{drop}}",
  dropAmp: "A_{\\mathrm{drop}}",
  dropV0: "v_{\\mathrm{drop}}",
  sites: "N",
  hop: "t",
  epsilon0: "\\epsilon_0",
  disorderW: "W",
  disorderSeed: "s_{\\mathrm{dis}}",
  periodic: "b_{\\mathrm{per}}",
  impuritySite: "n_{\\mathrm{imp}}",
  impurityStrength: "V_{\\mathrm{imp}}",
  slitSeparation: "d_{\\mathrm{slit}}",
  slitWidth: "w_{\\mathrm{slit}}",
  slitPhase: "\\phi_{\\mathrm{slit}}",
  slitAmpRatio: "r_{\\mathrm{slit}}",
  carrierK: "k_c",
  rightSlitOpen: "b_{\\mathrm{right}}",
  detectorY: "y_{\\mathrm{det}}",
  mass: "m",
  lambda: "\\lambda",
  damping: "\\eta",
  c0: "c_0",
  c1: "c_1",
  c2: "c_2",
  F0: "F_0",
  omegaDrive: "\\Omega_d",
  phiDrive: "\\phi_d",
  kT: "k_B T",
  fMax: "F_{\\max}",
  kPassive: "k_{\\mathrm{pas}}",
  lSlack: "l_{\\mathrm{slack}}",
  load: "F_{\\mathrm{load}}",
  lFloor: "l_{\\min}",
  D: "D",
  driftX: "u_x",
  driftY: "u_y",
  trapK: "k_{\\mathrm{trap}}",
  seed: "s",
  muK: "\\mu_k",
  ex0: "E_{x0}",
  ey0: "E_{y0}",
  sourceStrength: "\\kappa_s",
  coreRadius: "r_c",
  coreRadius1: "r_{c1}",
  coreRadius2: "r_{c2}",
  impactParam: "b",
  beamSpeed: "v_{\\infty}",
  edgeDamping: "\\eta_{\\mathrm{edge}}",
  uniformU: "U_0",
  uniformV: "V_0",
  inflowU: "U_{\\mathrm{in}}",
  obstacleX: "x_c",
  obstacleY: "y_c",
  obstacleR: "R",
  obstacleSoft: "\\delta_o",
  vortexStrength: "\\Gamma",
  rhoFluid: "\\rho_f",
  rhoParticle: "\\rho_p",
  radius: "r_p",
  cd: "C_d",
  mCart: "m_c",
  mPole: "m_p",
  omegaX: "\\Omega_x",
  omegaY: "\\Omega_y",
  omegaZ: "\\Omega_z",
  omega1x: "\\Omega_{1x}",
  omega1y: "\\Omega_{1y}",
  omega1z: "\\Omega_{1z}",
  omega2x: "\\Omega_{2x}",
  omega2y: "\\Omega_{2y}",
  omega2z: "\\Omega_{2z}",
  jzz: "J_{zz}",
  segments: "N",
  iterations: "N_{\\mathrm{iter}}",
  learningRate: "\\alpha",
  smoothness: "\\lambda_s",
  xClustering: "\\beta_x"
};

const systemParamTexOverrides: Record<string, Record<string, string>> = {
  tightbinding: {
    packetCenter: "n_0"
  },
  qftlattice: {
    packetCenter: "x_0"
  },
  percolation: {
    scanPoints: "N_p"
  }
};

export function getParamTexLabel(systemId: string | null, key: string): string | null {
  const override = systemId ? systemParamTexOverrides[systemId]?.[key] : undefined;
  if (typeof override === "string") {
    return override || null;
  }

  return globalParamTexByKey[key] ?? null;
}
